---
title: "clustering on auc"
author: "Luca"
date: '2022-05-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/Users/lucamainini/Documents/GitHub/AS_Project_2022')
```

## Import of data [to be skipped]

```{r functions}
#import nate's and luca's function
source(file.path("nate", "utils", "nate_utils.R"))
source(file.path("Luca", "luca_utils.R"))
```

```{r import data, eval=FALSE, include=FALSE}
#path="/Users/lucamainini/Documents/GitHub/AS_Project_2022/Dataset"
path="Dataset"
result <- import_dataset(path)
auc=result$auc
rpkm=result$rpkm
rm(result)
```

We work only on Breast cells

```{r selection of breast, eval=FALSE, include=FALSE}
#data_expression= read.delim(file.path("Dataset", "data_mrna_seq_rpkm.txt"), header = TRUE, comment.char = '#')
name_cols <- data_expression[,1]


sub_rpkm <-block_dat(cancers, rpkm) #otteniamo 46 valori invece dei 53 disponibili (in auc non li abbiamo li altri)
rpkm_breast <- cbind(sub_rpkm, name_cols)
View(sub_rpkm)
dim(sub_rpkm)
```

```{r eval=FALSE, include=FALSE}
breast_auc<-block_dat(c("BREAST"), auc)
breast_auc = t(breast_auc)

#apply Roberta's function
```

## LOAD DIRECTLY

```{r load data}
#save(breast_data_treatment_auc, file = "breast_auc_data.Rdata")
load(file.path("Dataset","breast_auc_data.Rdata"))
breast_auc = t(breast_data_treatment_auc)
```

```{r}
#install.packages("zoo")                                    # Install & load zoo package
library("zoo")
```

```{r substituting the NA with the average efficacy of the treatment}
breast_auc = na.aggregate(breast_auc)
```

```{r}
library(plotly)
fig <- plot_ly(
    x = colnames(breast_auc), y = rownames(breast_auc),
    colors = colorRamp(c("red", "green")),
    z = as.matrix(breast_auc), type = "heatmap"
)  
fig
```

```{r}
breast_auc = na.aggregate(breast_auc)
treatment_means = apply(breast_auc,2,mean)
plot(sort(treatment_means), type ="l")
#temp = treatment_means>0.98
#treatment_means[treatment_means>0.98]
group_1 <- (treatment_means<=0.80)
group_1 <- group_1*1
group_2 <- (treatment_means>0.80)&(treatment_means<=0.95)
group_2 <- group_2 *2
group_3 <- (treatment_means>0.95)
group_3 <- group_3*3
groups <- group_1+group_2+group_3
# > sum(group_1)
# [1] 41
# > sum(group_2)
# [1] 58
# > sum(group_3)
# [1] 44
plot(sort(treatment_means), type ="l", col=groups)
plot(treatment_means, col=groups+1)
```

```{r}
cell_means = apply(breast_auc,1,mean)
plot(sort(cell_means), type ="l")
group_1_c <- (cell_means<=0.83)
group_1_c <- group_1_c*1
group_2_c <- (cell_means>0.83)&(cell_means<=0.89)
group_2_c <- group_2_c *2
group_3_c <- (cell_means>0.89)
group_3_c <- group_3_c*3
groups_c <- group_1_c+group_2_c+group_3_c
# > sum(group_1)
# [1] 41
# > sum(group_2)
# [1] 58
# > sum(group_3)
# [1] 44
plot(cell_means, col=groups_c+1)
```
## PCA

```{r non scaled}
#data_5 = scale(breast_auc)
data_5 = breast_auc
cov2 = cov(data_5)
decomp2 = eigen(cov2)
#barplot(decomp2$values[1:50]/sum(decomp2$values), ylim = c(0,1))

# this is the projection matrix 
P2 = as.matrix(decomp2$vectors[,1:2])
reduced_M_ = data_5%*%P2
colnames(reduced_M_) <- c("v1","v2")

plot(reduced_M_, col = groups+1)

plot_ly(data = data.frame(reduced_M_), x = ~v1, y = ~v2,
                 type = "scatter") %>%
  layout(
      xaxis = list(range=c(0,7)),
      yaxis = list(range=c(0,7)))


P3 = as.matrix(decomp2$vectors[,1:3])
reduced_M_ = data_5%*%P3
colnames(reduced_M_) <- c("v1","v2", "v3")
data_plot = data.frame(reduced_M_)
data_plot$groups= groups_c
data_plot$cell_means= cell_means
# We try a 3D plot 
plot_ly(data = data_plot, x = ~v1, y = ~v2, z = ~v3,
        color = ~cell_means) %>% layout(title = 'Non Scaled PCA by cells AUC means')

plot_ly(data = data_plot, x = ~v1, y = ~v2, z = ~v3,
        color = ~groups_c) %>% layout(title = 'Non Scaled PCA by  AUC-means-based groups')
```
```{r}
fig <- plot_ly(
    #x = colnames(decomp2), y = rownames(decomp2$vectors),
    colors = colorRamp(c("red", "green")),
    z = as.matrix(decomp2$vectors), type = "heatmap"
)  
fig
```
```{r}
chosen <- decomp2$vectors[,2]>0.1
decomp2$vectors[decomp2$vectors[,2]>0.1,2]
indexes <- 1:144
indexes[decomp2$vectors[,2]>0.1]
fig <- plot_ly(
    #x = colnames(breast_auc), y = rownames(breast_auc),
    colors = colorRamp(c("red", "green")),
    z = as.matrix(data_5[,chosen]), type = "heatmap"
)  
fig
```


## HIERARCHICAL CLUSTERING

```{r}
library(mvtnorm)
library(rgl)
library(car)
```

```{r dissimilarity_matrix of ordered data}
# compute the dissimilarity matrix of the data
# we choose the Euclidean metric (and then we look at other metrics)

#help(dist)
d.e <- dist(data_5, method='euclidean')

image(1:44,1:44,as.matrix(d.e), main='metrics: Euclidean', asp=1, xlab='i', ylab='j')

# with other metrics:
d.m <- dist(data_5, method='manhattan')
d.c <- dist(data_5, method='canberra')

##xquartz()
par(mfrow=c(1,3))
image(1:44,1:44,as.matrix(d.e), main='metrics: Euclidean', asp=1, xlab='i', ylab='j' )
image(1:44,1:44,as.matrix(d.c), main='metrics: Canberra', asp=1, xlab='i', ylab='j' )
image(1:44,1:44,as.matrix(d.m), main='metrics: Manhattan', asp=1, xlab='i', ylab='j' )
```

```{r}
fig <- plot_ly(
    #x = colnames(data_5), y = rownames(data_5),
    #colors = colorRamp(c("red", "green")),
    z = as.matrix(d.e), type = "heatmap"
)  
fig
```

Le matrici sembrano simili, da cui ipotizziamo che cambiare la distanza non porterà a grandi differenze.

```{r euclidian}
d.es <- hclust(d.e, method='single')
d.ea <- hclust(d.e, method='average')
d.ec <- hclust(d.e, method='complete')

ward <- hclust(d.e, method='ward.D2')

# plot of the dendrograms
##xquartz()
par(mfrow=c(1,3))
plot(d.es, main='euclidean-single', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
plot(d.ec, main='euclidean-complete', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
plot(d.ea, main='euclidean-average', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')

# plot dendrograms (with eucledian it seems 2 clusters)
##xquartz()
par(mfrow=c(1,3))
plot(d.es, main='euclidean-single', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
rect.hclust(d.es, k=2)
plot(d.ec, main='euclidean-complete', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
rect.hclust(d.ec, k=3)
plot(d.ea, main='euclidean-average', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
rect.hclust(d.ea, k=3)

#plot(ward, hang=-0.1, labels=FALSE, main='ward', xlab='', sub='')

# How to cut a Dendrogram?
# We generate vectors of labels through the command cutree()
#help(cutree)

# Fix k=2 clusters:

cluster.es <- cutree(d.es, k=2) # euclidean-single
data_plot$cluster.es = cluster.es

cluster.ec <- cutree(d.ec, k=3) # euclidean-complete:
data_plot$cluster.ec = cluster.ec

cluster.ea <- cutree(d.ea, k=3) # euclidean-average
data_plot$cluster.ea = cluster.ea

cluster.ew <- cutree(ward, k=4) #ward divide il gruppo grosso in 2
data_plot$cluster.ew = cluster.ew

cluster.ew_3 <- cutree(ward, k=3) #ward divide il gruppo grosso in 2
data_plot$cluster.ew = cluster.ew_3
```

```{r}
plot_ly(data = data_plot, x = ~v1, y = ~v2, z = ~v3,
        color = ~cluster.es) %>% layout(title = 'Eucledian (single) Clusters plotted on first 3 PCs [non-scaled]')
```


```{r}
points3d(data_5[,1:3],col=color.outliers, asp=1, size=5)
title3d("OUTLIERS on first 3 treatments direction", )

open3d(windowRect=c(100,100,1000,1000))
plot3d(data_5, size=3, col=cluster.ew +1, aspect = F, xlab="AVA", ylab= 
          "BIC", zlab="LIN") 
title = deparse(substitute(cluster.w))
title3d(title)
axes3d()
name = paste(title, "png", sep = ".")
rgl.snapshot(filename = name)

open3d(windowRect=c(100,100,1000,1000))
plot3d(data_5, size=3, col=cluster.es +1, aspect = F, xlab="AVA", ylab= 
          "BIC", zlab="LIN") 
title = deparse(substitute(cluster.es))
title3d(title)
axes3d()
name = paste(title, "png", sep = ".")
rgl.snapshot(filename = name)


open3d(windowRect=c(100,100,1000,1000))
plot3d(data_5, size=3, col=cluster.ea +1, aspect = F, xlab="AVA", ylab= 
          "BIC", zlab="LIN") 
title = deparse(substitute(cluster.ea))
title3d(title)
axes3d()
name = paste(title, "png", sep = ".")
rgl.snapshot(filename = name)

open3d(windowRect=c(100,100,1000,1000))
plot3d(data_5, size=3, col=cluster.ec +1, aspect = F, xlab="AVA", ylab= 
          "BIC", zlab="LIN") 
title = deparse(substitute(cluster.ec))
title3d(title)
axes3d()
name = paste(title, "png", sep = ".")
rgl.snapshot(filename = name)
```

```{r}
pairs(data_5 , col=cluster.es+1, asp=1, pch=16, lwd=2)
pairs(data_5 , col=cluster.ec+1, asp=1, pch=16, lwd=2)
pairs(data_5 , col=cluster.ea+1, asp=1, pch=16, lwd=2)
pairs(data_5 , col=cluster.w+1, asp=1, pch=16, lwd=2)
```

```{r cophenetic}
coph.es <- cophenetic(d.es)
coph.ec <- cophenetic(d.ec)
coph.ea <- cophenetic(d.ea)
coph.w <- cophenetic(ward)

layout(rbind(c(0,1,0,0),c(2,3,4,5)))
image(as.matrix(d.e), main='Euclidean', asp=1 )
image(as.matrix(coph.es), main='Single', asp=1 )
image(as.matrix(coph.ec), main='Complete', asp=1 )
image(as.matrix(coph.ea), main='Average', asp=1 )
image(as.matrix(coph.w), main='Ward', asp=1 )

# compute cophenetic coefficients
es <- cor(d.e, coph.es)
ec <- cor(d.e, coph.ec)
ea <- cor(d.e, coph.ea)
ew <- cor(d.e, coph.w)
c("Eucl-Single"=es,"Eucl-Compl."=ec,"Eucl-Ave."=ea, "Ward"=ew )
```

AVERAGE 4 IS THE ONE RETAINED

```{r eval=FALSE, include=FALSE}
data_p = data.frame(data_5)
row.names(data_p)=row.names(data_5)
data_p$class = as.factor(cluster.ec)
ggpairs(data_p, # data.frame with variables
             columns = 1:5,
             aes(colour=class, alpha = 0.5)
        )

```

### CAMPERRA
```{r camperra}
d.cs <- hclust(d.c, method='single')
d.ca <- hclust(d.c, method='average')
d.cc <- hclust(d.c, method='complete')
d.cw <- hclust(d.c, method='ward.D2')

# plot of the dendrograms
##xquartz()
par(mfrow=c(1,3))
plot(d.cs, main='camperra-single', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
plot(d.cc, main='camperra-complete', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
plot(d.ca, main='camperra-average', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')

##xquartz()
par(mfrow=c(1,3))
plot(d.cs, main='camperra-single', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
rect.hclust(d.cs, k=2)
plot(d.cc, main='camperra-complete', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
rect.hclust(d.cc, k=2)
plot(d.ca, main='camperra-average', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
rect.hclust(d.ca, k=4)

#plot(d.cw, main='camperra-average', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
#rect.hclust(d.cw, k=2)

# How to cut a Dendrogram?
# We generate vectors of labels through the command cutree()
#help(cutree)

# Fix k=2 clusters:

cluster.cs <- cutree(d.cs, k=2) # camperra-single
data_plot$cluster.cs = cluster.cs
cluster.cc <- cutree(d.cc, k=2) # camperra-complete:
data_plot$cluster.cc = cluster.cc
cluster.ca <- cutree(d.ca, k=4) # camperra-average
data_plot$cluster.ca = cluster.ca
cluster.cw <- cutree(d.ca, k=2) # camperra-ward
data_plot$cluster.cw = cluster.cw

cluster.cw_3 <- cutree(d.ca, k=3) # camperra-ward
data_plot$cluster.cw_3 = cluster.cw_3

```

```{r plot_camperra}
plot_ly(data = data_plot, x = ~v1, y = ~v2, z = ~v3,
        color = ~cluster.cs) %>% layout(title = 'Camperra (single) Clusters plotted on first 3 PCs [non-scaled]')
```


```{r eval=FALSE, include=FALSE}

pairs(data_5 , col=cluster.cs+1, asp=1, pch=16, lwd=2)
pairs(data_5 , col=cluster.cc+1, asp=1, pch=16, lwd=2)
pairs(data_5 , col=cluster.ca+1, asp=1, pch=16, lwd=2)

open3d(windowRect=c(100,100,1000,1000))
plot3d(data_5, size=3, col=cluster.cw +1, aspect = F, xlab="AVA", ylab= 
          "BIC", zlab="LIN") 
title = deparse(substitute(cluster.cw))
title3d(title)
axes3d()
name = paste(title, "png", sep = ".")
rgl.snapshot(filename = name)

open3d(windowRect=c(100,100,1000,1000))
plot3d(data_5, size=3, col=cluster.cs +1, aspect = F, xlab="AVA", ylab= 
          "BIC", zlab="LIN") 
title = deparse(substitute(cluster.cs))
title3d(title)
axes3d()
name = paste(title, "png", sep = ".")
rgl.snapshot(filename = name)



open3d(windowRect=c(100,100,1000,1000))
plot3d(data_5, size=3, col=cluster.ca +1, aspect = F, xlab="AVA", ylab= 
          "BIC", zlab="LIN") 
title = deparse(substitute(cluster.ca))
title3d(title)
axes3d()
name = paste(title, "png", sep = ".")
rgl.snapshot(filename = name)


open3d(windowRect=c(100,100,1000,1000))
plot3d(data_5, size=3, col=cluster.cc +1, aspect = F, xlab="AVA", ylab= 
          "BIC", zlab="LIN") 
title = deparse(substitute(cluster.cc))
title3d(title)
axes3d()
name = paste(title, "png", sep = ".")
rgl.snapshot(filename = name)
```

```{r camperra cophenetic}
coph.cs <- cophenetic(d.cs)
coph.cc <- cophenetic(d.cc)
coph.ca <- cophenetic(d.ca)
coph.cw <- cophenetic(d.cw)

layout(rbind(c(0,1,0,0),c(2,3,4,5)))
image(as.matrix(d.e), main='camperra', asp=1 )
image(as.matrix(coph.cs), main='Single', asp=1 )
image(as.matrix(coph.cc), main='Complete', asp=1 )
image(as.matrix(coph.ca), main='Average', asp=1 )
image(as.matrix(coph.cw), main='Ward', asp=1 )

# compute cophenetic coefficients
cs <- cor(d.c, coph.cs)
cc <- cor(d.c, coph.cc)
ca <- cor(d.c, coph.ca)
cw <- cor(d.c, coph.cw)
c("Camp-Single"=cs,"Camp-Compl."=cc,"Camp-Ave."=ca, "Camp-Ward"=cw )
```
### MANHATTAN
```{r manhattan}
d.m <- dist(data_5, method='manhattan')
d.ms <- hclust(d.m, method='single')
d.ma <- hclust(d.m, method='average')
d.mc <- hclust(d.m, method='complete')

d.mw <- hclust(d.m, method='ward.D2')

# plot of the dendrograms
##xquartz()
par(mfrow=c(1,3))
plot(d.ms, main='manhattan-single', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
plot(d.mc, main='manhattan-complete', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
plot(d.ma, main='manhattan-average', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')

# plot dendrograms (with eucledian it seems 2 clusters)
##xquartz()
par(mfrow=c(1,3))
plot(d.ms, main='manhattan-single', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
rect.hclust(d.ms, k=3)
plot(d.mc, main='manhattan-complete', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
rect.hclust(d.mc, k=3)
plot(d.ma, main='manhattan-average', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
rect.hclust(d.ma, k=3)

#plot(ward, hang=-0.1, labels=FALSE, main='ward', xlab='', sub='')

# How to cut a Dendrogram?
# We generate vectors of labels through the command cutree()
#help(cutree)

# Fix k=2 clusters:
cluster.mc <- cutree(d.mc, k=3) # manhattan-complete
data_plot
cluster.ms <- cutree(d.ms, k=3) # manhattan-single
cluster.ma <- cutree(d.ma, k=3) # manhattan-average
cluster.mw <- cutree(d.mw, k=3) #ward divide il gruppo grosso in 2

data_plot$cluster.mc = cluster.mc
data_plot$cluster.ms = cluster.ms
data_plot$cluster.ma = cluster.ma
data_plot$cluster.mw = cluster.mw

```

```{r plot_manhattan}
plot_ly(data = data_plot, x = ~v1, y = ~v2, z = ~v3,
        color = ~cluster.ms) %>% layout(title = 'Manhattan (single) Clusters plotted on first 3 PCs [non-scaled]')
```

```{r}
open3d(windowRect=c(100,100,1000,1000))
plot3d(data_5, size=3, col=cluster.mw +1, aspect = F, xlab="AVA", ylab= 
          "BIC", zlab="LIN") 
title = deparse(substitute(cluster.mw))
title3d(title)
axes3d()
name = paste(title, "png", sep = ".")
rgl.snapshot(filename = name)

open3d(windowRect=c(100,100,1000,1000))
plot3d(data_5, size=3, col=cluster.ms +1, aspect = F, xlab="AVA", ylab= 
          "BIC", zlab="LIN") 
title = deparse(substitute(cluster.ms))
title3d(title)
axes3d()
name = paste(title, "png", sep = ".")
rgl.snapshot(filename = name)

open3d(windowRect=c(100,100,1000,1000))
plot3d(data_5, size=3, col=cluster.ma +1, aspect = F, xlab="AVA", ylab= 
          "BIC", zlab="LIN") 
title = deparse(substitute(cluster.ma))
title3d(title)
axes3d()
name = paste(title, "png", sep = ".")
rgl.snapshot(filename = name)

open3d(windowRect=c(100,100,1000,1000))
plot3d(data_5, size=3, col=cluster.mc +1, aspect = F, xlab="AVA", ylab= 
          "BIC", zlab="LIN") 
title = deparse(substitute(cluster.mc))
title3d(title)
axes3d()
name = paste(title, "png", sep = ".")
rgl.snapshot(filename = name)
```

```{r}
pairs(data_5 , col=cluster.ms+1, asp=1, pch=16, lwd=2)
pairs(data_5 , col=cluster.mc+1, asp=1, pch=16, lwd=2)
pairs(data_5 , col=cluster.ma+1, asp=1, pch=16, lwd=2)
pairs(data_5 , col=cluster.mw+1, asp=1, pch=16, lwd=2)
```

```{r manhattan cophenetic}
coph.ms <- cophenetic(d.ms)
coph.mc <- cophenetic(d.mc)
coph.ma <- cophenetic(d.ma)
coph.mw <- cophenetic(d.mw)

layout(rbind(c(0,1,0,0),c(2,3,4,5)))
image(as.matrix(d.e), main='manhattan', asp=1 )
image(as.matrix(coph.ms), main='Single', asp=1 )
image(as.matrix(coph.mc), main='Complete', asp=1 )
image(as.matrix(coph.ma), main='Average', asp=1 )
image(as.matrix(coph.mw), main='Ward', asp=1 )

# compute cophenetic coefficients
ms <- cor(d.m, coph.ms)
mc <- cor(d.m, coph.mc)
ma <- cor(d.m, coph.ma)
mw <- cor(d.m, coph.mw)
c("Mahn-Single"=es,"Mahn-Compl."=ec,"Mahn-Ave."=ea, "MahnWard"=ew )
```

## K-MEANS

```{r}
#result.k <- kmeans(data_5, centers=3) # Centers: fixed number of clusters
breast_auc = t(breast_data_treatment_auc)
data_5 = na.aggregate(breast_auc)

library(factoextra)
fviz_nbclust(data_5, FUN = kmeans, method = "silhouette") 
fviz_nbclust(data_5, FUN = kmeans, method = "wss")
# 3 clusters being optimal, could go to 7

# experimenting with the number of clusters
result.k <- kmeans(data_5, centers=3) # Centers: fixed number of clusters
data_plot$cluster.km_3 = result.k$cluster

#open3d(windowRect=c(100,100,1000,1000))
#plot3d(data_5, size=3, col=result.k$cluster +1, aspect = F, xlab="AVA", ylab= 
#           "BIC", zlab="LIN") 
# title = "K-means cluster (4)"
# title3d(title)
# axes3d()
# rgl.snapshot(filename = "auc_4_means.png")
```

```{r}
plot_ly(data = data_plot, x = ~v1, y = ~v2, z = ~v3,
        color = ~result.k$cluster) %>% layout(title = 'k=3 k-means')
```

